### ISSUE TITLE
Upgrade to Vulcain 2.0 ?

### ISSUE THREAD

**Issue by mrik974** [vulcainjs/vulcain-corejs#34]
It's more a question than an issue. 
I'm actually using vulcain-corejs `1.1.141`. 
Got back to coding after a few months and noticed vulcain 2.0.0-beta is out. 
Should I upgrade? What should I take care of if doing so ? Is there a page detailing the major changes ?

**Comment by malain** [comment]
Version 2 is a new major upgrade with many breaking changes specially due to code refactoring and concept renaming.

The two versions respect the same architecture and behaviors but you should make change manually if you want to migrate.

**Version 1 is no longer supported and must be considered as obsolete.**

Look at [Vulcain-Samples](http://github.com/vulcainjs/vulcain-samples) repository to get more informations.
